//! Achievements + the persistent stats layer behind them.
//!
//! Pure data and rules, no raylib: the game builds a `Snapshot` of whatever
//! the rules need, `Tracker.evaluate` returns what just unlocked, and the
//! backends (in-game toast, Steam via steam.zig, the save file) react.
//! Names and descriptions live here in both languages: they feed the in-game
//! toast/stats screen and the Steamworks entry sheet (docs/achievements.md,
//! generated by `zig build achievements-sheet`).

const std = @import("std");
const locale = @import("localization.zig");

/// Declaration order is the Steamworks display order: cheap early ones
/// first (they show on the store page), hidden easter eggs last.
pub const Id = enum(u8) {
    first_drop,
    super_bloom,
    full_crew,
    local_business,
    hive_mind,
    wholesale,
    long_live_the_queen,
    liquid_gold,
    field_of_giants,
    botanical_trifecta,
    circle_of_life,
    land_baron,
    well_read,
    royal_treatment,
    dynasty,
    perennial,
    bee_llionaire,
    swarm,
    // hidden
    night_shift,
    dont_poke_the_hive,
    sticky_situation,
};

pub const COUNT = @typeInfo(Id).@"enum".fields.len;

/// Lifetime counters mirrored as Steam stats. They live in the save file,
/// survive prestige *and* New Game (like Steam's own account-level stats).
pub const Stat = enum(u8) {
    lifetime_honey,
    prestige_count,
    super_flowers_merged,
    rotten_cleared,
    max_bees_alive,

    pub const COUNT = @typeInfo(Stat).@"enum".fields.len;

    pub const Kind = enum { int, float };

    /// Steamworks API name of the stat.
    pub fn api(self: Stat) [:0]const u8 {
        return @tagName(self);
    }

    pub fn kind(self: Stat) Kind {
        return switch (self) {
            .lifetime_honey => .float,
            else => .int,
        };
    }

    pub fn fromApi(api_name: []const u8) ?Stat {
        inline for (@typeInfo(Stat).@"enum".fields) |f| {
            if (std.mem.eql(u8, api_name, f.name)) return @enumFromInt(f.value);
        }
        return null;
    }
};

pub const Stats = struct {
    /// Honey earned by the colony, ever. f64: late-game runs sit in the
    /// trillions, past f32's exact-integer range.
    lifetimeHoney: f64 = 0,
    prestigeCount: u32 = 0,
    superFlowersMerged: u32 = 0,
    rottenCleared: u32 = 0,
    /// High-water mark of live bees.
    maxBeesAlive: u32 = 0,

    pub fn get(self: *const Stats, stat: Stat) f64 {
        return switch (stat) {
            .lifetime_honey => self.lifetimeHoney,
            .prestige_count => @floatFromInt(self.prestigeCount),
            .super_flowers_merged => @floatFromInt(self.superFlowersMerged),
            .rotten_cleared => @floatFromInt(self.rottenCleared),
            .max_bees_alive => @floatFromInt(self.maxBeesAlive),
        };
    }

    /// Set from a parsed save value; negative / non-finite input clamps to 0.
    pub fn set(self: *Stats, stat: Stat, value: f64) void {
        const v = if (std.math.isFinite(value)) @max(0, value) else 0;
        const asInt: u32 = @intFromFloat(@min(v, @as(f64, @floatFromInt(std.math.maxInt(u32)))));
        switch (stat) {
            .lifetime_honey => self.lifetimeHoney = v,
            .prestige_count => self.prestigeCount = asInt,
            .super_flowers_merged => self.superFlowersMerged = asInt,
            .rotten_cleared => self.rottenCleared = asInt,
            .max_bees_alive => self.maxBeesAlive = asInt,
        }
    }
};

pub const Progress = struct {
    stat: Stat,
    target: f64,
};

pub const Def = struct {
    id: Id,
    /// Steamworks API name.
    api: [:0]const u8,
    name_en: [:0]const u8,
    name_pt: [:0]const u8,
    desc_en: [:0]const u8,
    desc_pt: [:0]const u8,
    /// Hidden in Steamworks: description concealed until unlocked.
    hidden: bool = false,
    /// Milestone achievements get a Steam progress bar driven by this stat.
    progress: ?Progress = null,
};

// ---- thresholds --------------------------------------------------------------

pub const HONEY_FIRST_DROP: f64 = 1_000;
pub const HONEY_LOCAL_BUSINESS: f64 = 100_000;
pub const HONEY_LIQUID_GOLD: f64 = 1_000_000;
pub const HONEY_BEE_LLIONAIRE: f64 = 1_000_000_000;
pub const SUPER_FIELD_OF_GIANTS: u32 = 8;
pub const PRESTIGE_DYNASTY: u32 = 5;
pub const PRESTIGE_PERENNIAL: u32 = 10;
pub const JELLY_ROYAL_TREATMENT: u32 = 100;
pub const BEES_HIVE_MIND: u32 = 100;
pub const BEES_SWARM: u32 = 1_000_000;
pub const BEES_WHOLESALE: u32 = 100;
pub const ROTTEN_CIRCLE_OF_LIFE: u32 = 50;
pub const GRID_RING_LAND_BARON: u16 = 10;
pub const NIGHT_SHIFT_MAX_LEVEL: u16 = 4;
pub const HIVE_CLICKS_DONT_POKE: u32 = 20;
pub const FULL_STORAGE_SECONDS: f32 = 60;

pub const DEFS = [COUNT]Def{
    .{ .id = .first_drop, .api = "first_drop", .name_en = "First Drop", .name_pt = "Primeira Gota", .desc_en = "Earn 1,000 honey in total.", .desc_pt = "Ganhe 1.000 de mel ao todo.", .progress = .{ .stat = .lifetime_honey, .target = HONEY_FIRST_DROP } },
    .{ .id = .super_bloom, .api = "super_bloom", .name_en = "Super Bloom", .name_pt = "Superflorada", .desc_en = "Merge your first SUPER flower.", .desc_pt = "Funda sua primeira SUPERflor.", .progress = .{ .stat = .super_flowers_merged, .target = 1 } },
    .{ .id = .full_crew, .api = "full_crew", .name_en = "Full Crew", .name_pt = "Equipe Completa", .desc_en = "Own all four bee types at once.", .desc_pt = "Tenha os quatro tipos de abelha ao mesmo tempo." },
    .{ .id = .local_business, .api = "local_business", .name_en = "Local Business", .name_pt = "Negócio Local", .desc_en = "Earn 100,000 honey in total.", .desc_pt = "Ganhe 100.000 de mel ao todo.", .progress = .{ .stat = .lifetime_honey, .target = HONEY_LOCAL_BUSINESS } },
    .{ .id = .hive_mind, .api = "hive_mind", .name_en = "Hive Mind", .name_pt = "Mente de Colmeia", .desc_en = "Have 100 bees alive at once.", .desc_pt = "Tenha 100 abelhas vivas ao mesmo tempo.", .progress = .{ .stat = .max_bees_alive, .target = BEES_HIVE_MIND } },
    .{ .id = .wholesale, .api = "wholesale", .name_en = "Wholesale", .name_pt = "Atacado", .desc_en = "Buy 100 bees in a single purchase.", .desc_pt = "Compre 100 abelhas de uma só vez." },
    .{ .id = .long_live_the_queen, .api = "long_live_the_queen", .name_en = "Long Live the Queen", .name_pt = "Vida Longa à Rainha", .desc_en = "Prestige for the first time.", .desc_pt = "Faça prestígio pela primeira vez.", .progress = .{ .stat = .prestige_count, .target = 1 } },
    .{ .id = .liquid_gold, .api = "liquid_gold", .name_en = "Liquid Gold", .name_pt = "Ouro Líquido", .desc_en = "Earn 1,000,000 honey in total.", .desc_pt = "Ganhe 1.000.000 de mel ao todo.", .progress = .{ .stat = .lifetime_honey, .target = HONEY_LIQUID_GOLD } },
    .{ .id = .field_of_giants, .api = "field_of_giants", .name_en = "Field of Giants", .name_pt = "Campo de Gigantes", .desc_en = "Have 8 SUPER flowers alive at once.", .desc_pt = "Tenha 8 SUPERflores vivas ao mesmo tempo." },
    .{ .id = .botanical_trifecta, .api = "botanical_trifecta", .name_en = "Botanical Trifecta", .name_pt = "Trinca Botânica", .desc_en = "Have a SUPER rose, SUPER tulip and SUPER dandelion alive at the same time.", .desc_pt = "Tenha uma SUPER rosa, uma SUPER tulipa e um SUPER dente-de-leão vivos ao mesmo tempo." },
    .{ .id = .circle_of_life, .api = "circle_of_life", .name_en = "Circle of Life", .name_pt = "Ciclo da Vida", .desc_en = "Let your gardeners clear 50 rotten flowers.", .desc_pt = "Deixe suas jardineiras limparem 50 flores podres.", .progress = .{ .stat = .rotten_cleared, .target = ROTTEN_CIRCLE_OF_LIFE } },
    .{ .id = .land_baron, .api = "land_baron", .name_en = "Land Baron", .name_pt = "Barão das Terras", .desc_en = "Max out Grid Ring.", .desc_pt = "Leve o Anel da Grade ao nível máximo." },
    .{ .id = .well_read, .api = "well_read", .name_en = "Well Read", .name_pt = "Sabe-Tudo", .desc_en = "Purchase every one-shot node in the upgrade tree.", .desc_pt = "Compre todos os nós únicos da árvore de melhorias." },
    .{ .id = .royal_treatment, .api = "royal_treatment", .name_en = "Royal Treatment", .name_pt = "Tratamento Real", .desc_en = "Hold 100 unspent Royal Jelly.", .desc_pt = "Acumule 100 de Geleia Real sem gastar." },
    .{ .id = .dynasty, .api = "dynasty", .name_en = "Dynasty", .name_pt = "Dinastia", .desc_en = "Prestige 5 times.", .desc_pt = "Faça prestígio 5 vezes.", .progress = .{ .stat = .prestige_count, .target = PRESTIGE_DYNASTY } },
    .{ .id = .perennial, .api = "perennial", .name_en = "Perennial", .name_pt = "Perene", .desc_en = "Prestige 10 times.", .desc_pt = "Faça prestígio 10 vezes.", .progress = .{ .stat = .prestige_count, .target = PRESTIGE_PERENNIAL } },
    .{ .id = .bee_llionaire, .api = "bee_llionaire", .name_en = "Bee-llionaire", .name_pt = "Abelhionário", .desc_en = "Earn 1,000,000,000 honey in total.", .desc_pt = "Ganhe 1 bilhão de mel ao todo.", .progress = .{ .stat = .lifetime_honey, .target = HONEY_BEE_LLIONAIRE } },
    .{ .id = .swarm, .api = "swarm", .name_en = "BZZZZZZZZZZZZZ", .name_pt = "BZZZZZZZZZZZZZ", .desc_en = "Have 1,000,000 bees alive at once.", .desc_pt = "Tenha 1.000.000 de abelhas vivas ao mesmo tempo.", .progress = .{ .stat = .max_bees_alive, .target = BEES_SWARM } },
    .{ .id = .night_shift, .api = "night_shift", .name_en = "Night Shift", .name_pt = "Turno da Noite", .desc_en = "Max out Night Shift so the colony works through the whole night.", .desc_pt = "Leve o Turno da Noite ao máximo: a colônia trabalha a noite inteira.", .hidden = true },
    .{ .id = .dont_poke_the_hive, .api = "dont_poke_the_hive", .name_en = "Don't Poke the Hive", .name_pt = "Não Cutuque a Colmeia", .desc_en = "Click the hive 20 times in a row.", .desc_pt = "Clique na colmeia 20 vezes seguidas.", .hidden = true },
    .{ .id = .sticky_situation, .api = "sticky_situation", .name_en = "Sticky Situation", .name_pt = "Situação Pegajosa", .desc_en = "Sit at full honey storage for 60 seconds without spending.", .desc_pt = "Fique com o armazém de mel cheio por 60 segundos sem gastar nada.", .hidden = true },
};

comptime {
    for (DEFS, 0..) |d, i| {
        if (@intFromEnum(d.id) != i) @compileError("DEFS must be listed in Id order: " ++ d.api);
    }
}

pub fn def(id: Id) *const Def {
    return &DEFS[@intFromEnum(id)];
}

pub fn findByApi(api: []const u8) ?Id {
    for (&DEFS) |*d| {
        if (std.mem.eql(u8, d.api, api)) return d.id;
    }
    return null;
}

pub fn name(id: Id) [:0]const u8 {
    const d = def(id);
    return locale.tr(d.name_en, d.name_pt);
}

pub fn description(id: Id) [:0]const u8 {
    const d = def(id);
    return locale.tr(d.desc_en, d.desc_pt);
}

/// Everything the rules look at, sampled by the game once per tick.
pub const Snapshot = struct {
    stats: Stats = .{},
    beesAlive: u32 = 0,
    /// Indexed by components.BeeType: worker, swift, efficient, gardener.
    beeTypeCounts: [4]u32 = .{ 0, 0, 0, 0 },
    /// Live (non-rotten) SUPER flowers, and which types are represented
    /// (indexed by components.FlowerType: rose, tulip, dandelion).
    superFlowersAlive: u32 = 0,
    superTypesAlive: [3]bool = .{ false, false, false },
    /// Unspent Royal Jelly.
    availableJelly: u32 = 0,
    /// Most bees bought in one click since the last evaluation.
    largestPurchase: u32 = 0,
    allOneShotNodesOwned: bool = false,
    gridRingLevel: u16 = 0,
    nightShiftLevel: u16 = 0,
    hiveClickStreak: u32 = 0,
    fullStorageSeconds: f32 = 0,
};

pub fn isSatisfied(id: Id, s: *const Snapshot) bool {
    return switch (id) {
        .first_drop => s.stats.lifetimeHoney >= HONEY_FIRST_DROP,
        .local_business => s.stats.lifetimeHoney >= HONEY_LOCAL_BUSINESS,
        .liquid_gold => s.stats.lifetimeHoney >= HONEY_LIQUID_GOLD,
        .bee_llionaire => s.stats.lifetimeHoney >= HONEY_BEE_LLIONAIRE,
        .super_bloom => s.stats.superFlowersMerged >= 1,
        .field_of_giants => s.superFlowersAlive >= SUPER_FIELD_OF_GIANTS,
        .botanical_trifecta => s.superTypesAlive[0] and s.superTypesAlive[1] and s.superTypesAlive[2],
        .long_live_the_queen => s.stats.prestigeCount >= 1,
        .dynasty => s.stats.prestigeCount >= PRESTIGE_DYNASTY,
        .perennial => s.stats.prestigeCount >= PRESTIGE_PERENNIAL,
        .royal_treatment => s.availableJelly >= JELLY_ROYAL_TREATMENT,
        .full_crew => s.beeTypeCounts[0] > 0 and s.beeTypeCounts[1] > 0 and s.beeTypeCounts[2] > 0 and s.beeTypeCounts[3] > 0,
        .hive_mind => s.beesAlive >= BEES_HIVE_MIND,
        .swarm => s.beesAlive >= BEES_SWARM,
        .wholesale => s.largestPurchase >= BEES_WHOLESALE,
        .circle_of_life => s.stats.rottenCleared >= ROTTEN_CIRCLE_OF_LIFE,
        .well_read => s.allOneShotNodesOwned,
        .land_baron => s.gridRingLevel >= GRID_RING_LAND_BARON,
        .night_shift => s.nightShiftLevel >= NIGHT_SHIFT_MAX_LEVEL,
        .dont_poke_the_hive => s.hiveClickStreak >= HIVE_CLICKS_DONT_POKE,
        .sticky_situation => s.fullStorageSeconds >= FULL_STORAGE_SECONDS,
    };
}

/// Which achievements this profile has unlocked. Persisted in the save so
/// unlocks earned offline are known (and re-pushed to Steam on the next
/// connected launch).
pub const Tracker = struct {
    unlocked: [COUNT]bool = @splat(false),

    pub fn isUnlocked(self: *const Tracker, id: Id) bool {
        return self.unlocked[@intFromEnum(id)];
    }

    pub fn unlockedCount(self: *const Tracker) usize {
        var n: usize = 0;
        for (self.unlocked) |u| n += @intFromBool(u);
        return n;
    }

    /// Mark every satisfied, not-yet-unlocked achievement and return the
    /// newly unlocked ids (in display order) in `out`.
    pub fn evaluate(self: *Tracker, snapshot: *const Snapshot, out: *[COUNT]Id) []const Id {
        var n: usize = 0;
        for (&DEFS) |*d| {
            const i = @intFromEnum(d.id);
            if (self.unlocked[i]) continue;
            if (!isSatisfied(d.id, snapshot)) continue;
            self.unlocked[i] = true;
            out[n] = d.id;
            n += 1;
        }
        return out[0..n];
    }

    pub fn reset(self: *Tracker) void {
        self.unlocked = @splat(false);
    }
};

// ---- tests ----------------------------------------------------------------------

test "definitions are unique and consistent" {
    var seen = std.StringHashMap(void).init(std.testing.allocator);
    defer seen.deinit();
    for (&DEFS) |*d| {
        try std.testing.expect(!seen.contains(d.api));
        try seen.put(d.api, {});
        try std.testing.expect(d.name_en.len > 0 and d.name_pt.len > 0);
        try std.testing.expect(d.desc_en.len > 0 and d.desc_pt.len > 0);
        try std.testing.expectEqual(d.id, findByApi(d.api).?);
    }
    try std.testing.expectEqual(@as(?Id, null), findByApi("nope"));
    // Hidden ones sit at the end of the display order.
    var sawHidden = false;
    for (&DEFS) |*d| {
        if (d.hidden) sawHidden = true else try std.testing.expect(!sawHidden);
    }
}

test "a fresh profile satisfies nothing" {
    const snap = Snapshot{};
    for (&DEFS) |*d| try std.testing.expect(!isSatisfied(d.id, &snap));
}

test "honey milestones unlock in order from lifetime honey" {
    var t = Tracker{};
    var out: [COUNT]Id = undefined;
    var snap = Snapshot{};

    snap.stats.lifetimeHoney = 999;
    try std.testing.expectEqual(@as(usize, 0), t.evaluate(&snap, &out).len);

    snap.stats.lifetimeHoney = 1_000;
    const first = t.evaluate(&snap, &out);
    try std.testing.expectEqual(@as(usize, 1), first.len);
    try std.testing.expectEqual(Id.first_drop, first[0]);

    // Already unlocked ones never fire twice; a big jump fires all the rest.
    snap.stats.lifetimeHoney = 5e9;
    const rest = t.evaluate(&snap, &out);
    try std.testing.expectEqual(@as(usize, 3), rest.len);
    try std.testing.expectEqual(Id.local_business, rest[0]);
    try std.testing.expectEqual(Id.liquid_gold, rest[1]);
    try std.testing.expectEqual(Id.bee_llionaire, rest[2]);
    try std.testing.expectEqual(@as(usize, 0), t.evaluate(&snap, &out).len);
    try std.testing.expectEqual(@as(usize, 4), t.unlockedCount());
}

test "super flower rules" {
    var snap = Snapshot{};
    try std.testing.expect(!isSatisfied(.super_bloom, &snap));
    snap.stats.superFlowersMerged = 1;
    try std.testing.expect(isSatisfied(.super_bloom, &snap));

    snap.superFlowersAlive = 7;
    try std.testing.expect(!isSatisfied(.field_of_giants, &snap));
    snap.superFlowersAlive = 8;
    try std.testing.expect(isSatisfied(.field_of_giants, &snap));

    snap.superTypesAlive = .{ true, true, false };
    try std.testing.expect(!isSatisfied(.botanical_trifecta, &snap));
    snap.superTypesAlive = .{ true, true, true };
    try std.testing.expect(isSatisfied(.botanical_trifecta, &snap));
}

test "prestige rules" {
    var snap = Snapshot{};
    snap.stats.prestigeCount = 1;
    try std.testing.expect(isSatisfied(.long_live_the_queen, &snap));
    try std.testing.expect(!isSatisfied(.dynasty, &snap));
    snap.stats.prestigeCount = 5;
    try std.testing.expect(isSatisfied(.dynasty, &snap));
    try std.testing.expect(!isSatisfied(.perennial, &snap));
    snap.stats.prestigeCount = 10;
    try std.testing.expect(isSatisfied(.perennial, &snap));

    snap.availableJelly = 99;
    try std.testing.expect(!isSatisfied(.royal_treatment, &snap));
    snap.availableJelly = 100;
    try std.testing.expect(isSatisfied(.royal_treatment, &snap));
}

test "colony rules" {
    var snap = Snapshot{};
    snap.beeTypeCounts = .{ 5, 1, 1, 0 };
    try std.testing.expect(!isSatisfied(.full_crew, &snap));
    snap.beeTypeCounts = .{ 5, 1, 1, 1 };
    try std.testing.expect(isSatisfied(.full_crew, &snap));

    snap.beesAlive = 99;
    try std.testing.expect(!isSatisfied(.hive_mind, &snap));
    snap.beesAlive = 100;
    try std.testing.expect(isSatisfied(.hive_mind, &snap));
    try std.testing.expect(!isSatisfied(.swarm, &snap));
    snap.beesAlive = 1_000_000;
    try std.testing.expect(isSatisfied(.swarm, &snap));

    snap.largestPurchase = 99;
    try std.testing.expect(!isSatisfied(.wholesale, &snap));
    snap.largestPurchase = 100;
    try std.testing.expect(isSatisfied(.wholesale, &snap));

    snap.stats.rottenCleared = 50;
    try std.testing.expect(isSatisfied(.circle_of_life, &snap));
}

test "tree and easter-egg rules" {
    var snap = Snapshot{};
    snap.allOneShotNodesOwned = true;
    try std.testing.expect(isSatisfied(.well_read, &snap));
    snap.gridRingLevel = 9;
    try std.testing.expect(!isSatisfied(.land_baron, &snap));
    snap.gridRingLevel = 10;
    try std.testing.expect(isSatisfied(.land_baron, &snap));
    snap.nightShiftLevel = 4;
    try std.testing.expect(isSatisfied(.night_shift, &snap));
    snap.hiveClickStreak = 19;
    try std.testing.expect(!isSatisfied(.dont_poke_the_hive, &snap));
    snap.hiveClickStreak = 20;
    try std.testing.expect(isSatisfied(.dont_poke_the_hive, &snap));
    snap.fullStorageSeconds = 59.9;
    try std.testing.expect(!isSatisfied(.sticky_situation, &snap));
    snap.fullStorageSeconds = 60;
    try std.testing.expect(isSatisfied(.sticky_situation, &snap));
}

test "stats round-trip through the generic accessors" {
    var s = Stats{};
    s.set(.lifetime_honey, 1.5e12);
    s.set(.prestige_count, 7);
    s.set(.max_bees_alive, -3); // garbage clamps to 0
    s.set(.rotten_cleared, std.math.nan(f64));
    try std.testing.expectEqual(@as(f64, 1.5e12), s.get(.lifetime_honey));
    try std.testing.expectEqual(@as(u32, 7), s.prestigeCount);
    try std.testing.expectEqual(@as(u32, 0), s.maxBeesAlive);
    try std.testing.expectEqual(@as(u32, 0), s.rottenCleared);
    try std.testing.expectEqual(Stat.max_bees_alive, Stat.fromApi("max_bees_alive").?);
    try std.testing.expectEqual(@as(?Stat, null), Stat.fromApi("bogus"));
    try std.testing.expectEqual(Stat.Kind.float, Stat.lifetime_honey.kind());
    try std.testing.expectEqual(Stat.Kind.int, Stat.prestige_count.kind());
}

test "milestone progress targets match the rule thresholds" {
    try std.testing.expectEqual(HONEY_FIRST_DROP, def(.first_drop).progress.?.target);
    try std.testing.expectEqual(HONEY_BEE_LLIONAIRE, def(.bee_llionaire).progress.?.target);
    try std.testing.expectEqual(@as(f64, PRESTIGE_PERENNIAL), def(.perennial).progress.?.target);
    try std.testing.expectEqual(@as(f64, BEES_SWARM), def(.swarm).progress.?.target);
    try std.testing.expectEqual(@as(f64, ROTTEN_CIRCLE_OF_LIFE), def(.circle_of_life).progress.?.target);
}
