//! Generates docs/achievements.md — the Steamworks entry sheet (API names,
//! EN / PT-BR copy, hidden flags, progress stats, icon paths) — straight from
//! src/achievements.zig so the partner-site data can never drift from what
//! the game actually unlocks. Run with `zig build achievements-sheet`.

const std = @import("std");
const achievements = @import("achievements.zig");

const OUT_PATH = "docs/achievements.md";

pub fn main(init: std.process.Init) !void {
    var buf: [64 * 1024]u8 = undefined;
    var w = std.Io.Writer.fixed(&buf);

    try w.writeAll(
        \\# Steam achievements & stats
        \\
        \\<!-- GENERATED by `zig build achievements-sheet` from src/achievements.zig — edit the source, not this file. -->
        \\
        \\Entry sheet for the Steamworks partner site (App ID 4980570,
        \\**Stats & Achievements** tab). Achievement API names, copy in both
        \\languages, hidden flags and progress stats all come from
        \\`src/achievements.zig`; icons are rendered by
        \\`steam/achievements/render_icons.sh` into `steam/achievements/icons/`.
        \\
        \\## Stats (create these first)
        \\
        \\Persistent lifetime counters. They live in the save file, survive
        \\prestige and New Game, and are mirrored to Steam so milestone
        \\achievements get progress bars.
        \\
        \\| API name | Type | Meaning |
        \\|---|---|---|
        \\
    );
    inline for (@typeInfo(achievements.Stat).@"enum".fields) |f| {
        const stat: achievements.Stat = @enumFromInt(f.value);
        try w.print("| `{s}` | {s} | {s} |\n", .{ stat.api(), switch (stat.kind()) {
            .int => "INT",
            .float => "FLOAT",
        }, statMeaning(stat) });
    }

    try w.writeAll(
        \\
        \\Steamworks settings for every stat: *Increment only* = yes, *Max change* = unset, *Default* = 0.
        \\
        \\## Achievements (in display order)
        \\
        \\Enter them in this order — Steam shows the first few on the store
        \\page, so the cheap early ones go first and the hidden easter eggs
        \\last. *Progress* is the Steamworks "progress stat" (min 0, max as
        \\listed) that draws the bar on the achievement page.
        \\
        \\| # | API name | Name (EN) | Name (PT-BR) | Description (EN) | Description (PT-BR) | Hidden | Progress |
        \\|---|---|---|---|---|---|---|---|
        \\
    );
    for (&achievements.DEFS, 1..) |*d, n| {
        try w.print("| {d} | `{s}` | {s} | {s} | {s} | {s} | {s} | ", .{
            n, d.api, d.name_en, d.name_pt, d.desc_en, d.desc_pt, if (d.hidden) "**yes**" else "no",
        });
        if (d.progress) |p| {
            try w.print("`{s}` 0 → {d}", .{ p.stat.api(), @as(u64, @intFromFloat(p.target)) });
        } else {
            try w.writeAll("—");
        }
        try w.writeAll(" |\n");
    }

    try w.writeAll(
        \\
        \\Icons: `steam/achievements/icons/unlocked/<api>.png` and
        \\`steam/achievements/icons/locked/<api>.png` (64×64, PNG); 256×256
        \\masters sit in `icons/256/`. `contact_sheet.png` shows the whole set.
        \\
        \\## How unlocking works
        \\
        \\- `src/achievements.zig` holds the rules (`isSatisfied`) and the
        \\  `Tracker` of what this profile has unlocked. The game samples a
        \\  `Snapshot` twice a second and unlocks whatever newly qualifies.
        \\- Unlocks are recorded in the save file (`achievement <api>` lines)
        \\  together with the lifetime counters (`stat <api> <value>`), so they
        \\  persist offline and survive prestige / New Game.
        \\- `src/steam.zig` loads the Steamworks redistributable at **runtime**
        \\  (`libsteam_api.so` / `steam_api64.dll` next to the executable) and
        \\  calls `SetAchievement` + `StoreStats`. No SDK at build time; when the
        \\  library or the Steam client is missing everything is a no-op. On
        \\  every connected launch all local unlocks are re-asserted, so offline
        \\  unlocks land on the profile later.
        \\- In-game feedback: a banner at the top of the screen and a
        \\  `[achievements] unlocked <api>` line on stderr.
        \\
        \\## Testing
        \\
        \\**Without Steam** (unit tests + local backend):
        \\
        \\- `zig build test` runs the rule tests in `src/achievements.zig` and the
        \\  save round-trip tests.
        \\- `just achievements` starts a windowed run on a staged save that sits
        \\  one step from several triggers (Hive Mind, First Drop, Full Crew,
        \\  Wholesale, Land Baron…): buy a bee, watch the banners, check stderr.
        \\- `BT_RESET_ACHIEVEMENTS=1` wipes local unlocks + stats (and Steam's,
        \\  when connected) so a trigger can be replayed.
        \\
        \\**With Steam** (real overlay toasts):
        \\
        \\1. Create the stats + achievements above in Steamworks and click
        \\   **Publish** on the Stats & Achievements page (unpublished
        \\   definitions are invisible to the API — `SetAchievement` returns
        \\   false).
        \\2. Download the Steamworks SDK from the partner site and copy
        \\   `redistributable_bin/linux64/libsteam_api.so` (and
        \\   `win64/steam_api64.dll` for the Windows depot) into the repo root.
        \\   Both are gitignored.
        \\3. Run the Steam client logged into an account that owns the app
        \\   (developer accounts do), then `just steam-dev` — it writes
        \\   `steam_appid.txt` and launches windowed. Expect
        \\   `[steam] connected (app 4980570)` on stderr.
        \\4. Unlock something; Steam pops its own toast and the achievement shows
        \\   on the profile. `BT_RESET_ACHIEVEMENTS=1 just steam-dev` clears the
        \\   profile's achievements + stats through `ResetAllStats` to retest.
        \\
        \\`steam/stage.sh` copies the redistributables into the depot when
        \\present; the shipped build then loads them from its own folder.
        \\
    );

    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = OUT_PATH, .data = w.buffered() });
    std.debug.print("wrote {s} ({d} achievements, {d} stats)\n", .{ OUT_PATH, achievements.COUNT, achievements.Stat.COUNT });
}

fn statMeaning(stat: achievements.Stat) []const u8 {
    return switch (stat) {
        .lifetime_honey => "Honey earned by the colony, ever (survives prestige).",
        .prestige_count => "Times the player has prestiged.",
        .super_flowers_merged => "SUPER flowers merged, lifetime.",
        .rotten_cleared => "Rotten flowers cleared by gardener bees (Composting / Cleanup Crew).",
        .max_bees_alive => "High-water mark of live bees.",
    };
}
